name: Android UI Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2

      - name: Start Appium
        run: |
          appium --log appium.log --log-timestamp --allow-cors &
          sleep 10

      - name: Enable KVM
        run: |
          sudo chown $USER /dev/kvm || true

      - name: Run Emulator and Execute Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu off -no-audio -no-boot-anim -camera-back none
          disable-spellchecker: true

          script: |
            echo "=============================="
            echo "Aguardando emulator..."
            echo "=============================="

            adb wait-for-device

            until [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" == "1" ]]; do
              sleep 2
            done

            echo "=============================="
            echo "Criando pasta apps"
            echo "=============================="

            mkdir -p apps

            echo "=============================="
            echo "Baixando APK"
            echo "=============================="

            curl -L \
              -o apps/android.wdio.native.app.v2.2.0.apk \
              https://github.com/webdriverio/native-demo-app/releases/download/v2.2.0/android.wdio.native.app.v2.2.0.apk

            echo "=============================="
            echo "Instalando APK"
            echo "=============================="

            adb install -r apps/android.wdio.native.app.v2.2.0.apk

            echo "=============================="
            echo "Pacotes instalados"
            echo "=============================="

            adb shell pm list packages | grep wdiodemoapp

            echo "=============================="
            echo "Executando testes"
            echo "=============================="

            npm run test:android

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Appium Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log